#!/usr/bin/env pythonNone
# -*- coding: utf-8 -*-
#
# Copyright (c) 2018, German Aerospace Center (DLR)
#
# This file is part of the development version of FRASER.
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Authors:
# - 2018, Annika Ofenloch (DLR RY-AVS)

---
  # -----------------------------------------------------------------------
  # Update inventory file and the group variables
  # -----------------------------------------------------------------------
- name: Check if folders exists
  file: path="{{ item }}" state=directory
  loop:
    - "../ansible/inventory"
    - "../ansible/inventory/group_vars/all"
    
  # Create hosts file (inventory file)
- name: Build hosts file
  command: python3 ../fraser/scripts/hostsGenerator.py -f {{ hosts_config_filepath }} -d ../ansible/
  changed_when: False
- meta: refresh_inventory

  # Define global variables
- name: Build variables file
  command: python3 ../fraser/scripts/modelsVarsGenerator.py -f {{ hosts_config_filepath }} -d ../ansible/
  changed_when: False

- name: Include main.yml file in group_vars/all (includes global variables)
  include_vars:
   file: "../ansible/inventory/group_vars/all/main.yml"